### ISSUE TITLE
Add stistools SPP and CL functions from IRAF

### ISSUE THREAD

**Issue by SaraOgaz** [spacetelescope/stistools#15]
SPP:
 - [ ] Add doppinfo functionality #8
 - [ ] Add odelaytime functionality #9

CL:
 - [ ] Add ctestis functionality #10
 - [ ] Add defringe functionality #11
 - [ ] Add mkfringeflat functionality #12
 - [ ] Add normspflat functionality #13
 - [ ] Add prepspec functionality #14
