### ISSUE TITLE
Add new stistools wrappers for tasks added to HSTCAL

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/stistools#4]
- [ ] Add inttag task wrapper #5
 - [x] Add ovac2air task wrapper #6
 - [ ] Add tastis task wrapper #7

**Comment by SaraOgaz** [comment]
ovac2air Python replacement already exists, STIS team approved, so no longer need our own.

**Comment by SaOgaz** [comment]
Not adding anything to hstcal, closing
